repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        types: [python]
        args: ["--line-length=90"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
        types: [python]
        # args to make flake8 work with SQLAlchemy queries, and Black
        F403,F405: allow usage of import from *
        E711,E712: allow '==' and '== or != None' on sqlalchemy
        E402: allow inserting to path to import from utils modules
        E203,E501,W503: https://black.readthedocs.io/en/stable/the_black_code_style.html
        args:
          [
            "--max-line-length=90",
            "--ignore=E203,F401,F403,F405,E402,E501,W503,E711,E712",
          ]

      - id: check-ast
        types: [python]

      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]

      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]

      - id: detect-private-key

      - id: end-of-file-fixer

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
